"""initial schema

Revision ID: e4b2a9d21b3f
Revises: 
Create Date: 2026-10-02 07:17:22.027955
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4b2a9d21b3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdsco_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_product_name', sa.String(length=200), nullable=False),
    sa.Column('batch_number', sa.String(length=80), nullable=False),
    sa.Column('manufactured_by', sa.String(length=180), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('nsq_result', sa.Text(), nullable=False),
    sa.Column('reporting_source', sa.String(length=160), nullable=False),
    sa.Column('reporting_lab_state', sa.String(length=100), nullable=True),
    sa.Column('reporting_month', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cdsco_alerts_batch_number'), 'cdsco_alerts', ['batch_number'], unique=False)
    op.create_index(op.f('ix_cdsco_alerts_normalized_product_name'), 'cdsco_alerts', ['normalized_product_name'], unique=False)
    op.create_table('disease_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('disease', sa.String(length=160), nullable=False),
    sa.Column('concentration', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_signals_region'), 'disease_signals', ['region'], unique=False)
    op.create_table('external_source_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=160), nullable=False),
    sa.Column('disease_category', sa.String(length=120), nullable=True),
    sa.Column('therapeutic_category', sa.String(length=120), nullable=True),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_normalized_name'), 'medicines', ['normalized_name'], unique=True)
    op.create_table('seasonal_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_category', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_category', 'region', 'month', name='uq_seasonal_factor_scope')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('decision_candidates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('trigger', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_state_priority', 'decision_candidates', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_decision_candidates_trigger'), 'decision_candidates', ['trigger'], unique=False)
    op.create_table('demand_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('demand', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_demand_medicine_location_date', 'demand_history', ['medicine_id', 'location_id', 'period_date'], unique=False)
    op.create_table('inventory_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_id', 'location_id', 'batch_number', name='uq_batch_medicine_location')
    )
    op.create_index('ix_inventory_location_expiry', 'inventory_batches', ['location_id', 'expiry_date'], unique=False)
    op.create_table('inventory_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('safety_stock_days', sa.Integer(), nullable=False),
    sa.Column('max_cover_days', sa.Integer(), nullable=False),
    sa.Column('redistribution_cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stockout_penalty_per_unit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_id', 'location_id', name='uq_policy_medicine_location')
    )
    op.create_table('nppa_reference_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quoted_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('quoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('regulatory_notes', sa.Text(), nullable=True),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'medicine_id', name='uq_supplier_offer_medicine')
    )
    op.create_table('supplier_quality_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=80), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=False),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('precipitation_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('data_origin', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('candidate_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_status', sa.String(length=30), nullable=False),
    sa.Column('selected_action', sa.JSON(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('simulation_results', sa.JSON(), nullable=False),
    sa.Column('expected_impact', sa.JSON(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verification_details', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('audit', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['decision_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_decision_id'), 'audit_events', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_decision_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('decisions')
    op.drop_table('weather_observations')
    op.drop_table('supplier_transactions')
    op.drop_table('supplier_quality_events')
    op.drop_table('supplier_offers')
    op.drop_table('nppa_reference_prices')
    op.drop_table('inventory_policies')
    op.drop_index('ix_inventory_location_expiry', table_name='inventory_batches')
    op.drop_table('inventory_batches')
    op.drop_index('ix_demand_medicine_location_date', table_name='demand_history')
    op.drop_table('demand_history')
    op.drop_index(op.f('ix_decision_candidates_trigger'), table_name='decision_candidates')
    op.drop_index('ix_candidate_state_priority', table_name='decision_candidates')
    op.drop_table('decision_candidates')
    op.drop_table('suppliers')
    op.drop_table('seasonal_factors')
    op.drop_index(op.f('ix_medicines_normalized_name'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_table('locations')
    op.drop_table('external_source_status')
    op.drop_index(op.f('ix_disease_signals_region'), table_name='disease_signals')
    op.drop_table('disease_signals')
    op.drop_index(op.f('ix_cdsco_alerts_normalized_product_name'), table_name='cdsco_alerts')
    op.drop_index(op.f('ix_cdsco_alerts_batch_number'), table_name='cdsco_alerts')
    op.drop_table('cdsco_alerts')
    # ### end Alembic commands ###